@extends('layouts_web.app')

@section('content')
    <div class="container">
        <h1>
            Body
        </h1>
        <h1>
            Body
        </h1>
        <h1>
            Body
        </h1>
        <h1>
            Body
        </h1>
        <h1>
            Body
        </h1>
        <h1>
            Body
        </h1>
        <h1>
            Body
        </h1>
        <h1>
            Body
        </h1>
        <h1>
            Body
        </h1>
        <h1>
            Body
        </h1>
    </div>
@endsection
